### ISSUE TITLE
Will this work with geojson data?

### ISSUE THREAD

**Issue by Spartanace1024** [oscarfonts/mapbox-gl-cordova-offline#18]
Right now I currently have geojson being loaded offline using the below code. I'm using Ionic and up until production build everything had been working flawlessly, i'm hoping your plugin could help me out 👍 .

```
    this.map.addSource(this.STATES_SOURCE_ID, {
      type: "geojson",
      data: "/assets/data/map/us-states.geojson"
    });
```

Will this plugin work for this data type as well?

Thanks in advance!

**Comment by oscarfonts** [comment]
You can read geojson data directly with mapboxgl, no need for this plugin.
Just use an absolute path (starting with `file:///` if it's a local resource).

This plugin is for reading local vector `.mbtiles` files.

**Comment by Spartanace1024** [comment]
Awesome I actually was able to stumble into that. My file path was incorrect. Thanks for you time!
