### ISSUE TITLE
Marker is not working

### ISSUE THREAD

**Issue by eraysezginer** [oscarfonts/mapbox-gl-cordova-offline#22]
Hello,

I try to use simple marker (and other kind of mapbox features like LineString) but it's not showing on the map.Here is the code ;

        var map = new mapboxgl.OfflineMap({
            container: 'map',
             style: 'styles/osm-bright/style-offline.json',
            center: [2.15, 41.38],
            zoom: 8
        });

        var marker = new mapboxgl.Marker()
          .setLngLat([2.15, 41.38])
          .addTo(map);

But when I switch to online version with same code (OfflineMap-->Map) it works and shows the marker ;

        var map = new mapboxgl.Map({
            container: 'map',
             style: 'styles/osm-bright/style-offline.json',
            center: [2.15, 41.38],
            zoom: 8
        });

        var marker = new mapboxgl.Marker()
          .setLngLat([2.15, 41.38])
          .addTo(map);

What could be the reason, any idea?

Thank you

**Comment by oscarfonts** [comment]
OfflineMap returns a promise, not a map directly. See readme.
