### ISSUE TITLE
MBTiles Problem

### ISSUE THREAD

**Issue by eraysezginer** [oscarfonts/mapbox-gl-cordova-offline#37]
Hi,
I'm using your project for offline map application. I bought couple of maps from openmaptiles and they are working without any problems. Only problem is file size is too big for a small area and I need some other layers like(hillshade and contour ) so need another solutions so now I have 2 questions;

- When I  download a map from openstreetmap as osm or geojson and convert it to MBtiles, it's not working (map is not showing on app). Both(from openmaptiles and other one) of are MBtiles what is the difference and why it's not working?

- Is there any method to edit MBtiles file? Because I need a predefined small area but MBtiles file show whole world(of course not detailed but anyway it includes). 

Looking forward for your response

**Comment by michogar** [comment]
Hi @eraysezginer 

we use multiple sources to generate our MBTiles, in fact, we have published a demo applicacion with a mix of layers, the base map from OpenMapTiles and an overlay layer with the cadastral buildings in 3D. You can see the app here

https://play.google.com/store/apps/details?id=co.geomati.menorcaoffline

If you change the mbtiles you should fit the styles to the new layers. Maybe this is the problem, but without more info it's very difficult to find the problem.

You can build your own MBtiles with the info that you need. With OpenMapTiles the whole world in low detail are in every file. If you need to decrease the file size you should to build your own mbtiles.

Regardinng to the edition of mbtiles, I'm not completely sure what that it's mean. To show the MBtiles you can use QGIS with the Vector Tiles Reader. I'm not sure if you can use this plugin to edit the MBtiles as an usual GIS layer, you can try it!!.

https://plugins.qgis.org/plugins/vector_tiles_reader/

Best.
