### ISSUE TITLE
Map on IOS slowing down and eventually crashes

### ISSUE THREAD

**Issue by rklerck** [oscarfonts/mapbox-gl-cordova-offline#6]
When using the plugin on IOS 11 (iPhone 6), the map is really fast at the beginning but slows down with every zoom/move. Eventually the app crashes. I already changed the cache size to 0.

I stil see a memory problem:

```
2017-11-05 16:26:01.381482+0100 Store Check App[1322:52411] Got memory pressure notification (critical)
Message from debugger: Terminated due to memory issue
```

Do you have any ideas? I know you didn't test it on IOS...

**Comment by oscarfonts** [comment]
Sorry, no clue.
May look at it in the future, when I have a proper iOS testing environment available.

**Comment by oscarfonts** [comment]
@rklerck is this still an issue with the latest versions? If it is, please reopen.
